apiVersion: management.diegocloud.io/v1alpha1
kind: Environment
metadata:
  name: staging
spec:
  generatedHostDomain: diego.{{{ DOMAIN }}}
  applications: 
  - name: env-prerequisites
    versionRef:
      name: env-prerequisites-0.1.0
    overrideValues: |
      secrets_role_arn: "arn:aws:iam::{{{ AWS_ACCOUNT_ID }}}:role/DiegoAppSecretsReaderRoleStaging"
