apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-applications
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/{{{ ORG_NAME }}}/default-project.git
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: applications